name: today
favicon: null
layout_spectrum: 0.46462
typography_spectrum: 0.46671
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060f0c'
    - '#a2a2a2'
    - '#415062'
    - '#efece7'
    - '#930d18'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
